name: Check CDP Versions

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    name: Trigger Protocol Build
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4.14.x
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout CDP
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Checkout devtools-protocol
        uses: actions/checkout@v5
        with:
          repository: ChromeDevTools/devtools-protocol
          path: devtools-protocol
          fetch-depth: 0

      - name: Check for modified version in devtools-protocol
        id: git-check
        run: |
          cd devtools-protocol
          last_commit=$(git log --pretty="%B" | grep "Roll protocol to " | head -1 | cat);
          echo "$last_commit";
          cdp_version=$(echo "$last_commit" | grep -o "[0-9]\+");
          echo "$cdp_version";
          cd ..
          modified=$(npm version --no-git-tag-version "0.0.$cdp_version" &> /dev/null && echo true || echo false);
          echo "Modified $modified";
          echo "cdp_version=$cdp_version" >> $GITHUB_OUTPUT
          echo "modified=$modified" >> $GITHUB_OUTPUT

      - if: steps.git-check.outputs.modified == 'true'
        name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - if: steps.git-check.outputs.modified == 'true'
        name: Install dependencies
        run: opam install . --locked --deps-only --with-test --yes

      - if: steps.git-check.outputs.modified == 'true'
        name: Build OCaml bindings
        run: |
          rm ./lib/Types.ml ./lib/Events.ml ./lib/Commands.ml
          opam exec -- dune exec -- cdp ./devtools-protocol/json/browser_protocol.json ./devtools-protocol/json/js_protocol.json ./lib
          opam exec -- ocamlformat --inplace ./lib/*.ml
          opam exec -- dune build -p cdp

      - if: steps.git-check.outputs.modified == 'true'
        name: Commit update
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git commit -am "Roll protocol to r${{ steps.git-check.outputs.cdp_version }}"
          git push
