name: Check CDP Versions

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - ci

jobs:
  build:
    name: Trigger Protocol Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Reason CDP
        uses: actions/checkout@v2

      - name: Checkout devtools-protocol
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: ChromeDevTools/devtools-protocol
          path: devtools-protocol

      - name: Check for modified version in devtools-protocol
        id: git-check
        run: |
          ls -l
          cd devtools-protocol
          last_commit=$(git log -1 --pretty="%B" | cat);
          echo $last_commit;
          cdp_version=$($last_commit | grep -Eo "\d+");
          echo $cdp_version;
          cd ..
          modified=$(npm version --no-git-tag-version "0.0.$cdp_version" &> /dev/null && echo true || echo false);
          echo Modified $modified;
          branch_exists=$(git rev-parse --verify $cdp_version &> /dev/null && echo true || echo false);
          echo Branch exists $branch_exists;
          echo "::set-output name=cdp_version::$cdp_version";
          echo "::set-output name=modified::$modified";
          echo "::set-output name=branch_exists::$branch_exists";

      - if: steps.git-check.outputs.modified == 'true' && steps.git-check.outputs.branch_exists == 'false'
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - if: steps.git-check.outputs.modified == 'true' && steps.git-check.outputs.branch_exists == 'false'
        name: Install esy
        run: |
          npm install -g esy

      - if: steps.git-check.outputs.modified == 'true' && steps.git-check.outputs.branch_exists == 'false'
        uses: esy/github-action@master
        with:
          cache-key: ${{ matrix.os }}-${{ hashFiles('esy.lock/index.json') }}

      - if: steps.git-check.outputs.modified == 'true' && steps.git-check.outputs.branch_exists == 'false'
        name: Build Reason bindings
        run: |
          rm ./lib/Types.re ./lib/Events.re ./lib/Commands.re
          esy x cdp ./devtools-protocol/json/browser_protocol.json ./devtools-protocol/json/js_protocol.json ./lib
          esy refmt --in-place ./lib/Types.re ./lib/Events.re ./lib/Commands.re
          esy

      - if: steps.git-check.outputs.modified == 'true' && steps.git-check.outputs.branch_exists == 'false'
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: $(cd devtools-protocol && git log -1 --pretty=%B | cat | grep -Eo "Roll protocol to r.*")
          committer: GitHub Action <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: ${{ steps.git-check.outputs.cdp_version }}
          delete-branch: false
          title: Roll protocol to r${{ steps.git-check.outputs.cdp_version }}
